<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#learning-from-htm.core-community-fork-specific-tutorial" data-toc-modified-id="learning-from-htm.core-community-fork-specific-tutorial-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>learning from htm.core community fork specific tutorial</a></span><ul class="toc-item"><li><span><a href="#default-TemporalMemory-values" data-toc-modified-id="default-TemporalMemory-values-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>default TemporalMemory values</a></span></li></ul></li></ul></div>

# learning from htm.core community fork specific tutorial

https://3rdman.de/2020/02/hierarchical-temporal-memory-part-1-getting-started/

this is great, since nupic's original python 2.7 and htm.core python 3 is much different. it feels like the difference between Keras and Pytorch, really

In [1]:
# creating sample input sequence
import numpy as np

cycleArray = np.arange(0, 10, 1)
print(cycleArray)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# TM needs at least 8 active bits to work properly, interesting
# 10 possible numbers, 8 active bits for each #, put array_size = 80
import numpy as np

cycleArray = np.arange(0, 10, 1)
print(cycleArray)
def formatArray(array):
    result = ''
    for i in range(array.size):
        if i>0 and i%8 == 0:
            result += ' '
        result += format(array[i],'.0f')
    return result

arraySize = 80
cycleArray = np.arange(0, 10, 1)



for sensorValue in cycleArray:
    sensorValueBits = np.zeros(arraySize)
    sensorValueBits[sensorValue * 9: sensorValue * 8 + 8] = 1
    
    print('V:' + format(sensorValue, '>2')  + ' |', formatArray(sensorValueBits))
#     print(format(sensorValue, '>2') + ' |', sensorValueBits)

V: 0 | 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 1 | 00000000 01111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 2 | 00000000 00000000 00111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 3 | 00000000 00000000 00000000 00011111 00000000 00000000 00000000 00000000 00000000 00000000
V: 4 | 00000000 00000000 00000000 00000000 00001111 00000000 00000000 00000000 00000000 00000000
V: 5 | 00000000 00000000 00000000 00000000 00000000 00000111 00000000 00000000 00000000 00000000
V: 6 | 00000000 00000000 00000000 00000000 00000000 00000000 00000011 00000000 00000000 00000000
V: 7 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000 00000000
V: 8 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 9 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000


In [8]:
from htm.bindings.sdr import SDR
help(htm.bindings.sdr.SDR)

Help on class SDR in module htm.bindings.sdr:

class SDR(pybind11_builtins.pybind11_object)
 |  Sparse Distributed Representation
 |  
 |  This class manages the specification and momentary value of a Sparse Distributed
 |  Representation (SDR).  An SDR is a group of boolean values which represent the
 |  state of a group of neurons or their associated processes.
 |  
 |  SDR's have three commonly used data formats which are:
 |  *   dense
 |  *   sparse
 |  *   coordinates
 |  The SDR class has three magic properties, one for each of these data formats.
 |  These properties are the primary way of accessing the SDR's data.  When these
 |  properties are read from, the data is automatically converted to the requested
 |  format and is cached so getting a value in one format many times incurs no extra
 |  performance cost.  Assigning to the SDR via any one of these properties clears
 |  the cached values and causes them to be recomputed as needed.
 |  
 |  Example usage:
 |      # Make a

## note on SDR value reassignments:
avoid the python-C++ copy operation with inplace .dense modification -> reassign to self. class will detect it's being given its own data, and omits copy operation


In [9]:
X = SDR((1000,1000))
data = X.dense # assign X's value to data
type(data) # data is just a numpy array now

numpy.ndarray

In [10]:
data.shape

(1000, 1000)

In [11]:
data[0,4] = 1
data[444,444] = 1

In [12]:
X.sparse

array([], dtype=uint32)

In [13]:
X.dense = data
X.sparse

array([     4, 444444], dtype=uint32)

In [14]:
cycleArray = np.arange(0, 10, 1)
print(cycleArray)
def formatArray(array):
    result = ''
    for i in range(array.size):
        if i>0 and i%8 == 0:
            result += ' '
        result += format(array[i],'.0f')
    return result

arraySize = 80
cycleArray = np.arange(0, 10, 1)
inputSDR = SDR(arraySize)


for sensorValue in cycleArray:
    sensorValueBits = inputSDR.dense # assign to SDR
    sensorValueBits = np.zeros(arraySize)
    sensorValueBits[sensorValue * 9: sensorValue * 8 + 8] = 1
    inputSDR.dense = sensorValueBits
    
    print('V:' + format(sensorValue, '>2')  + ' |', formatArray(sensorValueBits))

[0 1 2 3 4 5 6 7 8 9]
V: 0 | 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 1 | 00000000 01111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 2 | 00000000 00000000 00111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 3 | 00000000 00000000 00000000 00011111 00000000 00000000 00000000 00000000 00000000 00000000
V: 4 | 00000000 00000000 00000000 00000000 00001111 00000000 00000000 00000000 00000000 00000000
V: 5 | 00000000 00000000 00000000 00000000 00000000 00000111 00000000 00000000 00000000 00000000
V: 6 | 00000000 00000000 00000000 00000000 00000000 00000000 00000011 00000000 00000000 00000000
V: 7 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000 00000000
V: 8 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
V: 9 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000


## default TemporalMemory values
- cellsPerColumn: int = 32
- activationThreshold: int = 13
- initialPermanence: float = 0.21
- connectedPermanence: float = 0.5
- minThreshold: int = 10
- maxNewSynapseCount: int = 20
- permanenceIncrement: float = 0.1
- permanenceDecrement: float = 0.1
- predictedSegmentDecrement: float = 0.0
- seed: int = 42
- maxSegmentsPerCell: int = 255
- maxSynapsesPerSegment: int = 255
- checkInputs: bool = True
- externalPredictiveInputs: int = 0
- anomalyMode: htm.bindings.algorithms.ANMode = ANMode.RAW

In [17]:
from htm.bindings.algorithms import TemporalMemory


In [ ]:
# for example reasons, we have 1 cell per column
# this make this... not really temporal, however.

In [20]:
cycleArray = np.arange(0, 10, 1)
print(cycleArray)
def formatSdr(sdr):
    result = ''
    for i in range(sdr.size):
        if i > 0 and i % 8 == 0:
            result += ' '
        result += str(sdr.dense.flatten()[i])
    return result

arraySize = 80
cycleArray = np.arange(0, 10, 1)
inputSDR = SDR(arraySize)

tm = TemporalMemory(columnDimensions = (inputSDR.size,),
        cellsPerColumn = 1,       # default: 32
        minThreshold = 4,         # default: 10
        activationThreshold = 8,  # default: 13
        initialPermanence = 0.5,  # default: 0.21
        )

for cycle in range(2): # 2 training cycles!
    for sensorValue in cycleArray:
        sensorValueBits = inputSDR.dense # assign to SDR
        sensorValueBits = np.zeros(arraySize)
        sensorValueBits[sensorValue * 9: sensorValue * 8 + 8] = 1
        inputSDR.dense = sensorValueBits

        tm.compute(inputSDR, learn=True)
        print('V:' + format(sensorValue, '>2')  + ' |', formatSdr(tm.getActiveCells()), 'Active')

        tm.activateDendrites(True) # activate the dendrites. what else would it do?
        print(format(tm.anomaly, '.2f') + ' |', formatSdr(tm.getPredictiveCells()), 'Predicted')

[0 1 2 3 4 5 6 7 8 9]
V: 0 | 11111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Active
1.00 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Predicted
V: 1 | 00000000 01111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Active
1.00 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Predicted
V: 2 | 00000000 00000000 00111111 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Active
1.00 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Predicted
V: 3 | 00000000 00000000 00000000 00011111 00000000 00000000 00000000 00000000 00000000 00000000 Active
1.00 | 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 Predicted
V: 4 | 00000000 00000000 00000000 00000000 00001111 00000000 00000000 00000000 00000000 00000000 Active
1.00 | 00000000 00000000 00000